[package]
name = "keychain"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.3.1", features = ["derive"] }
diesel = { version = "2.1.0", features = ["sqlite"] }
dotenvy = "0.15.7"
