CREATE TABLE IF NOT EXISTS keys (
  id INTEGER PRIMARY KEY NOT NULL,
  keychain_id INTEGER,
  name VARCHAR(50) NOT NULL UNIQUE,
  value VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(keychain_id) REFERENCES keychains(id) ON DELETE CASCADE
)